### ISSUE TITLE
Address Various Minor Issues from Kati's Testing

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-signs-markings#156]
- [x] As a viewer, clicked EDIT for a WO in NEED TO BE ISSUED, “To Cross Street” appeared even though it was an intersection type location. This is a required field so I could not update WO.

- [x] Adding asset on Locations details. Chose any action and the action field disappeared. Have to refresh page to get action field back.

- [ ] Asset Table only showing Name, Additional Message, Direction, Delete. Missing Condition and action.

- [ ] Everything was taking really long to load. Not sure if that was just my internet or something with the system but thought it was worth mentioning.

- [ ] “Back to Work Order Details” button at bottom of Location details page doesn’t have the back icon or the larger letters anymore.

- [x] The “Technician(s)” field when adding time doesn’t seem to be filtered to be just signs and markings technicians.

- [x] Change “Vehicles” field to multiselect. Signs largely works as individual technicians but if multiple trucks are at a job for some reason, we need the option to add more than one.

- [ ] Remove materials calculator link for signs work orders on work order details page. The calculators are only for markings related materials.

- [ ] Can we change the “no material” material to “no materials used” and hide the quantity field?

 
- [ ] Different column when adding the additional message than the existing messages for other signs I added additional messages for. When I add the message in the “Add Message” column, it refreshes and populates the “Message” column and the “Add Message” column goes away. Not sure if this is how it was intended to function? It still works but kind of weird to have the separate column to add, then it disappears.

**Comment by johnclary** [comment]
@dianamartin i fixed the "action" display issue by removing the display rule: If SPECIFICATION_NAME is not blank then hide/show SPECIFICATION NAME, and that resolved the issue. I couldn't tell what that rule was meant to do. Hope I didn't break something else. It seemed fine and logical when I tested all the action types.

I also updated the vehicles to have a many to many relationship with time logs, which will allow multi-select as requested.

And I set the technician filter on time logs to show technicians and technician supervisors.

**Comment by amenity** [comment]
@dianamartin - please add your email response here & close.

**Comment by dianamartin** [comment]
•	As a viewer, clicked EDIT for a WO in NEED TO BE ISSUED, “To Cross Street” appeared even though it was an intersection type location. This is a required field so I could not update WO.
>Fixed this, a couple display rules were “is” and should have been “is not” on the non-technician edit forms. 
•	Adding asset on Locations details. Chose any action and the action field disappeared. Have to refresh page to get action field back.
>John fixed this, there was an additional display rule
•	Asset Table only showing Name, Additional Message, Direction, Delete. Missing Condition and action.
>I logged in as Test Technician and added an asset and saw “Condition” and “Action”. Were you logged in as a different user role? 
•	Everything was taking really long to load. Not sure if that was just my internet or something with the system but thought it was worth mentioning. 

•	“Back to Work Order Details” button at bottom of Location details page doesn’t have the back icon or the larger letters anymore. 
>I see that..I wonder if they did it only on the Test environment..?
•	The “Technician(s)” field when adding time doesn’t seem to be filtered to be just signs and markings technicians. 
>@Clary, John I changed your filter since I was using “Title” as the field that differentiated technicians. The way you had it still showed other people.
•	Change “Vehicles” field to multiselect. Signs largely works as individual technicians but if multiple trucks are at a job for some reason, we need the option to add more than one. 
>John fixed this connection allowing for multiselect function.
•	Remove materials calculator link for signs work orders on work order details page. The calculators are only for markings related materials.
>I removed this for signs Materials form
•	Can we change the “no material” material to “no materials used” and hide the quantity field?
I fixed the field name and made a rule to hide quantity.
•	Different column when adding the additional message than the existing messages for other signs I added additional messages for. When I add the message in the “Add Message” column, it refreshes and populates the “Message” column and the “Add Message” column goes away. Not sure if this is how it was intended to function? It still works but kind of weird to have the separate column to add, then it disappears. 
>Yes, this was the way I had intended it. Did you have a suggestion to change this? Or did you want to keep the “Add Message” column?
 
•	Bread crumb trail chanced to Signs Work Orders. Not sure at exactly what point it happened but I was doing a maintenance ticket created by a tech and when I hit submit for review, I realized the bread crumb had been switched to signs work orders instead of the my work orders page that the techs should be going back to
 >I can change this, I think we changed this in Test and not in Prod. Changed
