### ISSUE TITLE
Test Geospatial UI on Lenovo Tablet w/ Mifi

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-knack-signs-markings#60]
@mddilley have you had a chance to do any testing on the Lenovo tablet? @dianamartin can probably help. the sooner the better. cc @mateoclarke

**Comment by mddilley** [comment]
@johnclary I have not been able to log on to the Lenovo Tablet yet. I've tried with a direct network connection and wifi, but my login credentials aren't allowing get past the login screen.

**Comment by mddilley** [comment]
@johnclary @dianamartin Just successfully logged in on the tablet.

**Comment by mddilley** [comment]
Testing these current geospatial features with the Lenovo Tablet w/ Mifi this morning.
- [ ] Work Order Details (Locations) view
- [ ] Add/remove location in Work Order Details view
- [ ] Single Location view
- [ ] Edit Location view
- [ ] Change location in Edit view

**Comment by dianamartin** [comment]
@mddilley You might also want to test
- [ ] Added Multiple locations
- [ ] Edit location of one location form multiple locations added
- [ ] Delete one location from multiple locations added

**Comment by mddilley** [comment]
@dianamartin @johnclary @mateoclarke After testing, I found that the geolocation coming from the browser isn't 100% reliable through Mifi. I checked the console and verified the coordinates being sent to the React app to rule out a bug in the map. I think the existing address input field is a good backup to this feature.

I also noticed that there are cases when the locations markers for existing locations don't immediately render (but will pop up once the map is moved or zoomed). I am looking into this since it could be confusing to the user to see a blank map in the View Location page.

**Comment by dianamartin** [comment]
@johnclary @mddilley @mateoclarke 
I've been testing on the tablets and the lenovos (last week and today)

## Tablet observations
- Adding Photo will make you click browse file but will give you a choice to add from photo gallery or use camera
- Modal pages work fine, but so do non-modal pages
- map is sensitive to scroll, so when a user is trying to scroll they might accidentally scroll on the map instead. (two finger zoom, might be helpful in order to stop this)
- Buttons and tables are pretty tiny, bumping up the sizes is going to be helpful.

## Lenovo observations
- I would suggest removing the keyboard, putting lenovo into tablet mode
- Typing on virtual keyboard wasn't too bad (tested inside a car, much less space than a truck)
- Must use Camera app first so that photo is in camera roll file bc on the tablet mode it doesn't give the option to use your camera, but only browse to a file like a desktop attachment.
- User must toggle between camera app and browser, but other than that not horrible. 

>I think they'll be able to work with the Lenovo hardware even if it's for a few weeks before the tablet roll out.

**Comment by mateoclarke** [comment]
@dianamartin, If there's anything you want us to work on from these observations will you spin it out as an issue and assign?

**Comment by dianamartin** [comment]
@mateoclarke Not sure if you guys can help with getting a camera app initiated from a Microsoft app or limiting zooming and panning of the map on a tablet unless two fingers are on the map..
